FROM fedora:latest

RUN sudo dnf -y upgrade && \
    sudo dnf -y install \
        make \
        mingw64-pkg-config \
        mingw64-gcc \
        mingw64-gcc-c++ \
        mingw64-SDL2 \
        mingw64-SDL2_mixer \
        mingw64-zlib \
        mingw64-bzip2 \
        mingw64-libpng \
        mingw64-winpthreads
