FROM fedora:latest

RUN sudo dnf -y upgrade && \
    sudo dnf -y install \
        make \
        mingw64-gcc \
        mingw64-gcc-c++ \
        mingw64-SDL2-static \
        mingw64-zlib-static \
        mingw64-bzip2-static \
        mingw64-libpng-static \
        mingw64-winpthreads-static
