name: CI
on:
  push:
    branches:
      - master

jobs:
  build-images:
    name: Build docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Credential Helper
        shell: bash
        run: sudo apt-get install pass
      - name: Build
        shell: bash
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: ./build-docker-images.sh
